<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Academic Info '), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Dashboard'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="dashboard"><?php echo $this->translate('Dashboard') ?> &raquo;</a></p>
</div>

<div class="row">
</div>